### ISSUE TITLE
Add e-mail notification service

### ISSUE THREAD

**Issue by ofaltins** [ofaltins/website-monitor#1]
Implement an e-mail notification service, i.e. MailGun

Use case:
When any monitor yields a valid result, trigger send a e-mail notification containing the monitor description, the content returned by the monitor and timestamp.

Notification should be triggered from here: https://github.com/ofaltins/website-monitor/blob/master/src/runMonitor.js#L53

**Comment by gsm005** [comment]
Hey I have written a python code for email alert/notification service. Will it be of any help? Should I PR it @ofaltins!

**Comment by ofaltins** [comment]
Hey! Thanks for reaching out, but that would make it harder to maintain this repo. Javascript only, please 🙏 @gsm005

**Comment by gsm005** [comment]
No worries👍.

**Comment by chankruze** [comment]
@ofaltins can I work on this using `nodemailer` ? If so, assign me this issue.

**Comment by ofaltins** [comment]
Sure thing @chankruze !

**Comment by ofaltins** [comment]
How's the work going @chankruze ?

**Comment by chankruze** [comment]
@ofaltins I have already working demo in my local machine using MailGun. Will commit soon. FYI the `API KEY` is being pulled from the environment variable. Will submit a PR soon.

**Comment by chankruze** [comment]
@ofaltins Need following info:

- [ ] recipient email id (to)
- [ ] sender email/name (from)

Above info are required for sending the e-mail:

```javascript
const messageData = {
  from: "Website Monitor <event@websitemonitor>",
  to: "listener@example.com",
  subject: `[${monitor.key}] Valid Result`,
  text: `Monitor ${monitor.description} yields VALID with content ${content} at ${now}`,
};
```
