### ISSUE TITLE
Design simple logo

### ISSUE THREAD

**Issue by ofaltins** [ofaltins/website-monitor#5]
It would be great to have a simple logo for the project

**Comment by chankruze** [comment]
I'll design a simple logo and favicon variants too.

**Comment by deepesh16b** [comment]
Please assign this to me
I can design the logo
@ofaltins

**Comment by adityaonstage** [comment]
i would love to contribute @ofaltins . I am a beginner. I wil do the stuff.

**Comment by ofaltins** [comment]
As @chankruze already has #1 to work on, i'll assign to @deepesh16b

**Comment by deepesh16b** [comment]
@ofaltins 
Hello Ofaltins,
What type of logo do you want?

**Comment by deepesh16b** [comment]
Please check this,
https://www.canva.com/design/DAEfm58GB_4/iAVAz2_MIPXMSU0QTNBAvw/edit?utm_content=DAEfm58GB_4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by ofaltins** [comment]
That's a good start @deepesh16b - can we get something similar to this: https://github.com/plumsirawit/task-pdf-writer/blob/main/README.md

You can use the same graphical elements with no color-gradients, and text: 
Website Monitor
Listen for changes on any website, for developers.

**Comment by deepesh16b** [comment]
> That's a good start @deepesh16b - can we get something similar to this: https://github.com/plumsirawit/task-pdf-writer/blob/main/README.md
> 
I didn't find any logo or image on the above link

**Comment by ofaltins** [comment]
@deepesh16b Here's a direct link to the .svg file: https://raw.githubusercontent.com/plumsirawit/task-pdf-writer/main/public/task-pdf-writer-banner.svg

**Comment by deepesh16b** [comment]
> @deepesh16b Here's a direct link to the .svg file: https://raw.githubusercontent.com/plumsirawit/task-pdf-writer/main/public/task-pdf-writer-banner.svg

sir its still not opening

**Comment by deepesh16b** [comment]
@ofaltins 
is this ok
![Untitled design](https://user-images.githubusercontent.com/70226498/194558109-0feacab3-5705-46f2-9556-b1cfb83f67b7.png)

**Comment by chankruze** [comment]
> > @deepesh16b Here's a direct link to the .svg file: https://raw.githubusercontent.com/plumsirawit/task-pdf-writer/main/public/task-pdf-writer-banner.svg
> 
> sir its still not opening
> 

It is opening kiddo. It's opening a svg logo of pdf-writer app.

@deepesh16b put that monitor a little bit down. Check the distance of the monitor's edeges from the circle. 

And always try to provide a direct link, no one wants to signup/login to see your design.

**Comment by deepesh16b** [comment]
![Untitled design (3)](https://user-images.githubusercontent.com/70226498/194559578-c6bbb62f-b591-4d5e-b451-dc9f1090dc3f.jpg)

**Comment by chankruze** [comment]
> 
> I have tried, its not opening on my pc
> can you send me a screenshot

Here is the svg logo itself: https://we.tl/t-htamF0JWfL

![Screenshot_2022-10-07-18-22-12-66.jpg](https://user-images.githubusercontent.com/29806845/194559825-158ae12f-0252-4dbe-b0f0-504d8599b716.jpg)

**Comment by deepesh16b** [comment]
@ofaltins 
please check this
![Untitled design (4)](https://user-images.githubusercontent.com/70226498/194695091-8cdf8de6-d7d8-4202-84f1-e4a3f5657cb8.jpg)

**Comment by ofaltins** [comment]
Looks good @deepesh16b ! Please submit a PR with the logo and i'll approve
