### ISSUE TITLE
Refactor: Enforce Code Formatting Rules

### ISSUE THREAD

**Issue by chankruze** [ofaltins/website-monitor#6]
@ofaltins I have also seen that there is currently inconsistency in the code files. For example, `cli.js` has 2 space indentation while others have 4 spaces.

So I'm proposing a style rule in `.editorconfig`.

![image](https://user-images.githubusercontent.com/29806845/194005312-b8a87770-f02a-411e-9a3f-61acf354aeb7.png)

![image](https://user-images.githubusercontent.com/29806845/194005275-f7bb6f4b-e11b-4ea1-b199-237d4d99604f.png)

**Comment by ofaltins** [comment]
Sweet! Looking forward to get it merged! 👊
